### ISSUE TITLE
Log in and log out

### ISSUE THREAD

**Issue by gitkc** [mfouladi/CollegeHotlineTest#11]
There are issues of cleanly logging in and out.

When a user closes the application or leaves the system, they should be logged out completely. If that is not easy, we should at least reset availability to only work when someone is on the conversations page or notes page.

**Comment by mfouladi** [comment]
Ended up doing exactly that. Using a timer on the server (only 3 seconds) it sets a parameter in the database every time a user changes a page. If the user goes back to one of the hotline pages (notes, volunteers, or text) then the parameter will be reset. Otherwise, the parameter remains set.
After the three seconds, the parameter is checked, and if it is set, the user is logged out.

**Comment by mfouladi** [comment]
Ended up doing exactly that. Using a timer on the server (only 3 seconds) it sets a parameter in the database every time a user changes a page. If the user goes back to one of the hotline pages (notes, volunteers, or text) then the parameter will be reset. Otherwise, the parameter remains set.
After the three seconds, the parameter is checked, and if it is set, the user is logged out.
